### ISSUE TITLE
JEI recipe transfer fails when too many possible ingredients are present

### ISSUE THREAD

**Issue by ferreiraalex** [tth05/morerefinedstorage#31]
all time when i press in jei + in refined storage on wood or plank( or may be somethink i have this 
i dont know what it happens but i press [plus] and this bug happen
https://pastebin.com/KDKKNDw3
and sapling too

**Comment by tth05** [comment]
I'm aware of this issue, but fixing it would require me to implement packet splitting afaik, which I do not plan on working on right now. 
The current fix should just send you a message and not allow the recipe transfer but that doesn't seem to be working correctly...

**Comment by tth05** [comment]
When did you get the error in #30? Do you not always get this one?

**Comment by tth05** [comment]
I've removed the error from the logs and fixed the error message not being sent in chat in 50bdbd562723409b428f81c60a3e198659e42ac0. I'll keep it like this for now.

**Comment by ferreiraalex** [comment]
now i play with much! so much items in world and have error with: sapling vanilla wood, wood, planks. its absolutlly tested on clear flat new world - bug repeat 
i now start simple modpack with 30~ mods try press + on sapling recipe and bug repeat 
https://i.imgur.com/PiEV5pD.png
https://pastebin.com/2hpp5xdc
and first time minecraft not respond, second time leave world
idk with what items it's can repeat. If you want if i have this error in my game later with another items i can write it here
and what time release? i play with yabba bug now from 20 days 😢

**Comment by embeddedt** [comment]
> i now start simple modpack with 30~ mods try press + on sapling recipe and bug repeat

What mods are they? The number of mods is not what matters; it's the number of new recipes/items added, as that is what makes the packet grow larger (based on my limited understanding).

**Comment by Pelotrio** [comment]
That happens because the maximum size for a packet payload in minecraft is 32767 bytes. The amount of different items that are a available for the current recipe all have to be sent to the client and can exceed that limit. This mostly happens if a lot of different items are valid for one recipe. For example sapplings, wood, leaves etc. would break if too many mods add variants of these items (oredict). This could only be fixed by either splitting the packet into multiple ones and then handling them on the sever side or increasing the limit but that would require a core-mod. What also would work is to catch the exception so it won't kick you but that is not a real fix.

**Comment by ferreiraalex** [comment]
now i absolutely understand the core of the problem. but 1-2 days ago no. Thanks for answer. and yes i think the full solution in core multiple. if creators can realize that that will be awesome. i check some bugs too, but tth05 fix it . now i think mod 99% fixed and work awesome. and ikd may be you are creators too. can i give some donate to creators? and ehat about release i no see more than 1 month but 2-3 fix happend((

**Comment by Pelotrio** [comment]
A release will happen if there are enough major changes. If you want to donate to him you have to ask him about that. If he keeps it like this so it does not work but also wont kick you I can create the core-mod I was talking about.

**Comment by ferreiraalex** [comment]
if you can create please did that. what about discord group? this mod no have? tth05 no have contact, only here. if you have discord write me please FerreiraAlex#6400 tth05 if you have group about this mod please write too

**Comment by tth05** [comment]
I've made a new release. Remember though that this does not fix the issue, it just prevents the error in the logs and saves you from being kicked.

**Comment by ferreiraalex** [comment]
and work with YABBA ! i m so happy!  make this trad open for waht we know about issue ok?

**Comment by Pelotrio** [comment]
@ferreiraalex I sent you a friend request on discord and also I am currently working on increasing the packet size limit. You can check that out here: https://github.com/Minecraft-TA/TotalPerformance. It already works in singleplayer if you want to try that out.
